"""Generate Bash completion from the command-line parser."""

from __future__ import annotations

import argparse
from pathlib import Path
import shlex

from yae.cli import create_parser
from yae.commands import create_commands


def generate_bash_completion() -> str:
    parser = create_parser(create_commands())
    parsers = {"": parser}
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            parsers.update(action.choices)

    lines = [
        "# Generated by python -m yae.completion; do not edit.",
        "_yae()",
        "{",
        "    local cur prev words cword split",
        "    _init_completion -s || return",
        "    local command='' pending='' word option kind i",
        "    local -A options=() kinds=() choices=() remainder=()",
    ]
    for name, command_parser in parsers.items():
        flags = []
        for action in command_parser._actions:
            flags.extend(action.option_strings)
            if action.nargs == argparse.REMAINDER:
                lines.append(f"    remainder[{shlex.quote(name)}]=1")
            for flag in action.option_strings:
                if action.nargs == 0:
                    continue
                key = shlex.quote(f"{name}:{flag}")
                kind = "directory" if action.type is Path else "value"
                lines.append(f"    kinds[{key}]={kind}")
                if action.choices is not None:
                    values = shlex.quote(" ".join(str(value) for value in action.choices))
                    lines.append(f"    choices[{key}]={values}")
        key = shlex.quote(name or ":")
        lines.append(f"    options[{key}]={shlex.quote(' '.join(flags))}")

    commands = shlex.quote(" ".join(name for name in parsers if name))
    lines.append(f"    local commands={commands}")
    lines.append(r'''
    for ((i = 1; i < cword; i++)); do
        word=${words[i]}
        if [[ $pending ]]; then
            pending=''
            continue
        fi
        [[ $word == -- ]] && return 0
        if [[ $word == -* ]]; then
            option=${word%%=*}
            if [[ ${kinds[$command:$option]-} && $word != *=* ]]; then
                pending=$option
            fi
        elif [[ ! $command ]]; then
            [[ ${options[$word]-} ]] || return 0
            command=$word
        elif [[ ${remainder[$command]-} ]]; then
            return 0
        fi
    done

    [[ $split == true ]] && pending=$prev
    if [[ $pending ]]; then
        kind=${kinds[$command:$pending]-}
        if [[ $kind == directory ]]; then
            _filedir -d
        elif [[ ${choices[$command:$pending]-} ]]; then
            mapfile -t COMPREPLY < <(compgen -W "${choices[$command:$pending]}" -- "$cur")
        fi
        return 0
    fi
    if [[ $cur == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${options[${command:-:}]}" -- "$cur")
    elif [[ ! $command ]]; then
        mapfile -t COMPREPLY < <(compgen -W "$commands" -- "$cur")
    fi
    return 0
}
complete -F _yae yae
'''.lstrip("\n"))
    return "\n".join(lines)


if __name__ == "__main__":
    print(generate_bash_completion(), end="")
