from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
import json
import os
import re
import shutil
import subprocess

from yae.errors import ProjectError


SUPPORTED_CPPLIBS = ("llvm-static", "gcc-static")
LINKER_TYPES = {
    "mold": "MOLD",
    "lld": "LLD",
    "ld": "BFD",
}
COMPILER_NAME = re.compile(r"(clang|gcc)(?:-(\d+))?")


@dataclass(frozen=True)
class YaeToolchain:
    compiler: str
    linker: str
    cpplib: str | None = None

    @classmethod
    def from_configuration(cls, value: object) -> YaeToolchain:
        if not isinstance(value, dict):
            raise ProjectError("yae-toolchain must be an object")

        unknown_keys = sorted(set(value) - {"compiler", "linker", "cpplib"})
        if unknown_keys:
            raise ProjectError(f"Unknown yae-toolchain option: {unknown_keys[0]}")

        compiler = value.get("compiler")
        if not isinstance(compiler, str) or COMPILER_NAME.fullmatch(compiler) is None:
            raise ProjectError("yae-toolchain compiler must be 'clang', 'gcc', or an exact version")

        linker = value.get("linker")
        if not isinstance(linker, str) or linker not in LINKER_TYPES:
            expected = ", ".join(LINKER_TYPES)
            raise ProjectError(f"Unknown yae-toolchain linker '{linker}'. Expected one of: {expected}")

        cpplib = value.get("cpplib")
        if cpplib is not None and cpplib not in SUPPORTED_CPPLIBS:
            expected = ", ".join(SUPPORTED_CPPLIBS)
            raise ProjectError(f"Unknown yae-toolchain cpplib '{cpplib}'. Expected one of: {expected}")
        if compiler.startswith("gcc") and cpplib is not None:
            raise ProjectError("yae-toolchain cpplib overrides require a Clang compiler")
        return cls(compiler=compiler, linker=linker, cpplib=cpplib)


def read_default_toolchain_configuration() -> object:
    path = Path(__file__).with_name("default_toolchain.json")
    with open(path, mode="r", encoding="utf-8") as file:
        return json.load(file)


def generate_toolchain_file(configuration: object, storage_dir: Path) -> Path:
    toolchain = YaeToolchain.from_configuration(configuration)
    c_compiler, cxx_compiler = _find_compilers(toolchain.compiler)

    lines = [
        "# Generated by YAE. Local machine configuration; do not commit.",
        f'set(CMAKE_C_COMPILER "{_cmake_path(c_compiler)}")',
        f'set(CMAKE_CXX_COMPILER "{_cmake_path(cxx_compiler)}")',
    ]
    if toolchain.compiler.startswith("clang"):
        lines.append(f'set(CMAKE_CUDA_COMPILER "{_cmake_path(cxx_compiler)}")')
    lines.append(f'set(CMAKE_LINKER_TYPE "{LINKER_TYPES[toolchain.linker]}" CACHE STRING "YAE linker type")')
    if toolchain.cpplib == "llvm-static":
        libcxx = _find_compiler_library(cxx_compiler, "libc++.a")
        libcxxabi = _find_compiler_library(cxx_compiler, "libc++abi.a")
        lines.extend(
            [
                'set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")',
                'set(CMAKE_CUDA_FLAGS_INIT "-stdlib=libc++")',
                'set(CMAKE_EXE_LINKER_FLAGS_INIT "-nostdlib++")',
                'set(CMAKE_SHARED_LINKER_FLAGS_INIT "-nostdlib++")',
                'set(CMAKE_MODULE_LINKER_FLAGS_INIT "-nostdlib++")',
                f'set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "{_cmake_path(libcxx)} {_cmake_path(libcxxabi)}")',
                f'set(CMAKE_CUDA_STANDARD_LIBRARIES_INIT "{_cmake_path(libcxx)} {_cmake_path(libcxxabi)}")',
            ]
        )
    elif toolchain.cpplib == "gcc-static":
        _find_compiler_library(cxx_compiler, "libstdc++.a")
        lines.extend(
            [
                'set(CMAKE_CXX_FLAGS_INIT "-stdlib=libstdc++")',
                'set(CMAKE_CUDA_FLAGS_INIT "-stdlib=libstdc++")',
                'set(CMAKE_EXE_LINKER_FLAGS_INIT "-static-libstdc++")',
                'set(CMAKE_SHARED_LINKER_FLAGS_INIT "-static-libstdc++")',
                'set(CMAKE_MODULE_LINKER_FLAGS_INIT "-static-libstdc++")',
            ]
        )

    fingerprint = sha256("\n".join(lines).encode()).hexdigest()[:16]
    lines.append(f'set(YAE_TOOLCHAIN_ID "{fingerprint}" CACHE INTERNAL "YAE toolchain identity")')
    contents = "\n".join(lines) + "\n"
    toolchains_dir = storage_dir / ".yae" / "toolchains"
    toolchains_dir.mkdir(parents=True, exist_ok=True)
    path = toolchains_dir / f"{fingerprint}.cmake"
    if not path.exists() or path.read_text(encoding="utf-8") != contents:
        path.write_text(contents, encoding="utf-8")
    return path


def _find_compilers(compiler: str) -> tuple[Path, Path]:
    match = COMPILER_NAME.fullmatch(compiler)
    assert match is not None
    family = match.group(1)
    requested_version = match.group(2)
    cxx_family = "clang++" if family == "clang" else "g++"
    if requested_version is not None:
        return _find_compiler_pair(f"{family}-{requested_version}", f"{cxx_family}-{requested_version}")

    unversioned_c = shutil.which(family)
    unversioned_cxx = shutil.which(cxx_family)
    if unversioned_c is not None and unversioned_cxx is not None:
        return Path(unversioned_c).absolute(), Path(unversioned_cxx).absolute()

    for version in sorted(_installed_compiler_versions(family), reverse=True):
        try:
            return _find_compiler_pair(f"{family}-{version}", f"{cxx_family}-{version}")
        except ProjectError:
            continue
    raise ProjectError(f"Could not find {family}/{cxx_family} or a matching versioned pair")


def _installed_compiler_versions(family: str) -> set[int]:
    versions: set[int] = set()
    versioned_name = re.compile(rf"{re.escape(family)}-(\d+)")
    for directory in os.get_exec_path():
        path = Path(directory)
        if not path.is_dir():
            continue
        for candidate in path.glob(f"{family}-*"):
            match = versioned_name.fullmatch(candidate.name)
            if match is not None:
                versions.add(int(match.group(1)))
    return versions


def _find_compiler_pair(c_name: str, cxx_name: str) -> tuple[Path, Path]:
    c_compiler = shutil.which(c_name)
    cxx_compiler = shutil.which(cxx_name)
    if c_compiler is None or cxx_compiler is None:
        raise ProjectError(f"Could not find matching {c_name} and {cxx_name} compilers")
    return Path(c_compiler).absolute(), Path(cxx_compiler).absolute()


def _find_compiler_library(cxx_compiler: Path, library_name: str) -> Path:
    try:
        result = subprocess.run(
            [cxx_compiler.as_posix(), f"--print-file-name={library_name}"],
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as error:
        raise ProjectError(f"Could not query {library_name} from {cxx_compiler}") from error

    library = Path(result.stdout.strip())
    if not library.is_absolute() or not library.is_file():
        raise ProjectError(f"Could not find {library_name} for {cxx_compiler}")
    return library.resolve()


def _cmake_path(path: Path) -> str:
    return path.as_posix().replace('"', '\\"')
