[project]
name = "yae"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.9.4",
]

[project.scripts]
yae = "yae.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/yae"]

[tool.pyright]
extraPaths = ["src"]
