from pathlib import Path

import pytest

from yae import toolchain
from yae.errors import ProjectError


def test_toolchain_requires_supported_compiler() -> None:
    with pytest.raises(ProjectError, match="compiler must be 'clang', 'gcc', or an exact version"):
        toolchain.YaeToolchain.from_configuration({"compiler": "msvc", "linker": "ld"})


def test_toolchain_requires_supported_linker() -> None:
    with pytest.raises(ProjectError, match="Unknown yae-toolchain linker 'gold'"):
        toolchain.YaeToolchain.from_configuration({"compiler": "gcc", "linker": "gold"})


def test_toolchain_rejects_unknown_cpplib() -> None:
    with pytest.raises(ProjectError, match="Unknown yae-toolchain cpplib 'llvm'"):
        toolchain.YaeToolchain.from_configuration({"compiler": "clang", "linker": "mold", "cpplib": "llvm"})


def test_toolchain_rejects_cpplib_override_for_gcc() -> None:
    with pytest.raises(ProjectError, match="cpplib overrides require a Clang compiler"):
        toolchain.YaeToolchain.from_configuration({"compiler": "gcc", "linker": "ld", "cpplib": "gcc-static"})


def test_toolchain_rejects_unknown_option() -> None:
    with pytest.raises(ProjectError, match="Unknown yae-toolchain option: compiler-version"):
        toolchain.YaeToolchain.from_configuration(
            {"compiler": "clang", "linker": "mold", "compiler-version": "22"}
        )


def test_unversioned_clang_is_preferred(monkeypatch) -> None:
    paths = {"clang": "/tools/clang", "clang++": "/tools/clang++"}
    monkeypatch.setattr(toolchain.shutil, "which", paths.get)

    assert toolchain._find_compilers("clang") == (Path("/tools/clang"), Path("/tools/clang++"))


def test_unversioned_gcc_is_preferred(monkeypatch) -> None:
    paths = {"gcc": "/tools/gcc", "g++": "/tools/g++"}
    monkeypatch.setattr(toolchain.shutil, "which", paths.get)

    assert toolchain._find_compilers("gcc") == (Path("/tools/gcc"), Path("/tools/g++"))


def test_highest_matching_clang_version_is_fallback(monkeypatch) -> None:
    paths = {
        "clang-18": "/tools/clang-18",
        "clang++-18": "/tools/clang++-18",
        "clang-20": "/tools/clang-20",
        "clang++-20": "/tools/clang++-20",
    }
    monkeypatch.setattr(toolchain.shutil, "which", paths.get)
    monkeypatch.setattr(toolchain, "_installed_compiler_versions", lambda family: {18, 20})

    assert toolchain._find_compilers("clang") == (Path("/tools/clang-20"), Path("/tools/clang++-20"))


def test_exact_clang_version_does_not_fallback(monkeypatch) -> None:
    paths = {"clang-21": "/tools/clang-21"}
    monkeypatch.setattr(toolchain.shutil, "which", paths.get)

    with pytest.raises(ProjectError, match=r"matching clang-21 and clang\+\+-21"):
        toolchain._find_compilers("clang-21")


def test_default_toolchain_uses_dynamic_libstdcxx_and_gnu_linker(tmp_path: Path, monkeypatch) -> None:
    c_compiler = tmp_path / "bin" / "gcc"
    cxx_compiler = tmp_path / "bin" / "g++"
    monkeypatch.setattr(toolchain, "_find_compilers", lambda compiler: (c_compiler, cxx_compiler))

    path = toolchain.generate_toolchain_file(
        toolchain.read_default_toolchain_configuration(),
        tmp_path / "storage",
    )

    assert path.read_text(encoding="utf-8") == (
        "# Generated by YAE. Local machine configuration; do not commit.\n"
        f'set(CMAKE_C_COMPILER "{c_compiler.as_posix()}")\n'
        f'set(CMAKE_CXX_COMPILER "{cxx_compiler.as_posix()}")\n'
        'set(CMAKE_LINKER_TYPE "BFD" CACHE STRING "YAE linker type")\n'
        f'set(YAE_TOOLCHAIN_ID "{path.stem}" CACHE INTERNAL "YAE toolchain identity")\n'
    )


def test_generated_llvm_toolchain_is_content_addressed(tmp_path: Path, monkeypatch) -> None:
    c_compiler = tmp_path / "bin" / "clang"
    cxx_compiler = tmp_path / "bin" / "clang++"
    libcxx = tmp_path / "lib" / "libc++.a"
    libcxxabi = tmp_path / "lib" / "libc++abi.a"
    monkeypatch.setattr(toolchain, "_find_compilers", lambda compiler: (c_compiler, cxx_compiler))
    monkeypatch.setattr(
        toolchain,
        "_find_compiler_library",
        lambda compiler, name: libcxx if name == "libc++.a" else libcxxabi,
    )

    first = toolchain.generate_toolchain_file(
        {"compiler": "clang", "linker": "mold", "cpplib": "llvm-static"},
        tmp_path / "storage",
    )
    second = toolchain.generate_toolchain_file(
        {"compiler": "clang", "linker": "mold", "cpplib": "llvm-static"},
        tmp_path / "storage",
    )

    assert first == second
    assert first.parent == tmp_path / "storage" / ".yae" / "toolchains"
    contents = first.read_text(encoding="utf-8")
    assert contents == (
        "# Generated by YAE. Local machine configuration; do not commit.\n"
        f'set(CMAKE_C_COMPILER "{c_compiler.as_posix()}")\n'
        f'set(CMAKE_CXX_COMPILER "{cxx_compiler.as_posix()}")\n'
        'set(CMAKE_LINKER_TYPE "MOLD" CACHE STRING "YAE linker type")\n'
        'set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")\n'
        'set(CMAKE_EXE_LINKER_FLAGS_INIT "-nostdlib++")\n'
        'set(CMAKE_SHARED_LINKER_FLAGS_INIT "-nostdlib++")\n'
        'set(CMAKE_MODULE_LINKER_FLAGS_INIT "-nostdlib++")\n'
        f'set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "{libcxx.as_posix()} {libcxxabi.as_posix()}")\n'
        f'set(YAE_TOOLCHAIN_ID "{first.stem}" CACHE INTERNAL "YAE toolchain identity")\n'
    )


def test_generated_gcc_static_toolchain_uses_clang_driver_options(tmp_path: Path, monkeypatch) -> None:
    c_compiler = tmp_path / "bin" / "clang-22"
    cxx_compiler = tmp_path / "bin" / "clang++-22"
    monkeypatch.setattr(toolchain, "_find_compilers", lambda compiler: (c_compiler, cxx_compiler))
    monkeypatch.setattr(toolchain, "_find_compiler_library", lambda compiler, name: tmp_path / "libstdc++.a")

    path = toolchain.generate_toolchain_file(
        {"compiler": "clang-22", "linker": "lld", "cpplib": "gcc-static"},
        tmp_path / "storage",
    )

    assert path.read_text(encoding="utf-8") == (
        "# Generated by YAE. Local machine configuration; do not commit.\n"
        f'set(CMAKE_C_COMPILER "{c_compiler.as_posix()}")\n'
        f'set(CMAKE_CXX_COMPILER "{cxx_compiler.as_posix()}")\n'
        'set(CMAKE_LINKER_TYPE "LLD" CACHE STRING "YAE linker type")\n'
        'set(CMAKE_CXX_FLAGS_INIT "-stdlib=libstdc++")\n'
        'set(CMAKE_EXE_LINKER_FLAGS_INIT "-static-libstdc++")\n'
        'set(CMAKE_SHARED_LINKER_FLAGS_INIT "-static-libstdc++")\n'
        'set(CMAKE_MODULE_LINKER_FLAGS_INIT "-static-libstdc++")\n'
        f'set(YAE_TOOLCHAIN_ID "{path.stem}" CACHE INTERNAL "YAE toolchain identity")\n'
    )
