# Generated by python -m yae.completion; do not edit.
_yae()
{
    local cur prev words cword split
    _init_completion -s || return
    local command='' pending='' word option kind i
    local -A options=() kinds=() choices=() remainder=()
    options[:]='-h --help -v --verbose --clone-progress'
    kinds[clone:--cloned_repositories_dir]=directory
    options[clone]='-h --help --cloned_repositories_dir'
    kinds[generate:--project_dir]=directory
    kinds[generate:--cloned_repositories_dir]=directory
    options[generate]='-h --help --project_dir --cloned_repositories_dir'
    kinds[configure:--project_dir]=directory
    kinds[configure:--cloned_repositories_dir]=directory
    kinds[configure:--build_dir]=directory
    remainder[configure]=1
    options[configure]='-h --help --project_dir --cloned_repositories_dir --build_dir'
    kinds[build:--project_dir]=directory
    kinds[build:--cloned_repositories_dir]=directory
    kinds[build:--build_dir]=directory
    options[build]='-h --help --project_dir --cloned_repositories_dir --build_dir'
    kinds[run:--project_dir]=directory
    kinds[run:--cloned_repositories_dir]=directory
    kinds[run:--build_dir]=directory
    remainder[run]=1
    options[run]='-h --help --project_dir --cloned_repositories_dir --build_dir'
    kinds[profile:--project_dir]=directory
    kinds[profile:--cloned_repositories_dir]=directory
    kinds[profile:--build_dir]=directory
    kinds[profile:--output]=directory
    kinds[profile:--frequency]=value
    kinds[profile:--event]=value
    kinds[profile:--call-graph]=value
    choices[profile:--call-graph]='fp dwarf'
    kinds[profile:--perf]=value
    remainder[profile]=1
    options[profile]='-h --help --project_dir --cloned_repositories_dir --build_dir --output --frequency --event --call-graph --perf --overwrite'
    kinds[test:--project_dir]=directory
    kinds[test:--cloned_repositories_dir]=directory
    kinds[test:--build_dir]=directory
    kinds[test:-j]=value
    kinds[test:--jobs]=value
    kinds[test:-R]=value
    kinds[test:--tests-regex]=value
    options[test]='-h --help --project_dir --cloned_repositories_dir --build_dir -j --jobs -R --tests-regex'
    kinds[list:--project_dir]=directory
    kinds[list:--cloned_repositories_dir]=directory
    options[list]='-h --help --project_dir --cloned_repositories_dir -e --executables -l --libraries --project --support --external --all --plain'
    kinds[git-status:--project_dir]=directory
    kinds[git-status:--cloned_repositories_dir]=directory
    options[git-status]='-h --help --project_dir --cloned_repositories_dir --all'
    kinds[format:--repository_dir]=directory
    kinds[format:--project_dir]=directory
    kinds[format:--tool]=value
    options[format]='-h --help --repository_dir --project_dir --all --tool'
    kinds[tidy:--repository_dir]=directory
    kinds[tidy:--project_dir]=directory
    kinds[tidy:--build_dir]=directory
    kinds[tidy:--tool]=value
    remainder[tidy]=1
    options[tidy]='-h --help --repository_dir --project_dir --build_dir --all --tool'
    kinds[cleanup:--project_dir]=directory
    options[cleanup]='-h --help --project_dir'
    kinds[self-test:--yae-root]=directory
    options[self-test]='-h --help --yae-root'
    local commands='clone generate configure build run profile test list git-status format tidy cleanup self-test'
    for ((i = 1; i < cword; i++)); do
        word=${words[i]}
        if [[ $pending ]]; then
            pending=''
            continue
        fi
        [[ $word == -- ]] && return 0
        if [[ $word == -* ]]; then
            option=${word%%=*}
            if [[ ${kinds[$command:$option]-} && $word != *=* ]]; then
                pending=$option
            fi
        elif [[ ! $command ]]; then
            [[ ${options[$word]-} ]] || return 0
            command=$word
        elif [[ ${remainder[$command]-} ]]; then
            return 0
        fi
    done

    [[ $split == true ]] && pending=$prev
    if [[ $pending ]]; then
        kind=${kinds[$command:$pending]-}
        if [[ $kind == directory ]]; then
            _filedir -d
        elif [[ ${choices[$command:$pending]-} ]]; then
            mapfile -t COMPREPLY < <(compgen -W "${choices[$command:$pending]}" -- "$cur")
        fi
        return 0
    fi
    if [[ $cur == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${options[${command:-:}]}" -- "$cur")
    elif [[ ! $command ]]; then
        mapfile -t COMPREPLY < <(compgen -W "$commands" -- "$cur")
    fi
    return 0
}
complete -F _yae yae
